name: adbonnin_flutter_carousel
description: A carousel widget for Flutter.
version: 1.0.0

homepage: https://github.com/adbonnin/flutter_carousel
repository: https://github.com/adbonnin/flutter_carousel

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
